version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - 6379:6379

  app:
    build:
      context: ..  # Parent dir (root projektu, gdzie pom.xml i src)
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005